### ISSUE TITLE
Fix Moon Rendering

### ISSUE THREAD

**Issue by xSoaa** [kobraworksmodding/Saints-Row-2-Juiced-Patch#7]
We're still unsure what is actually causing the moon to not render, although if its found to not be a chunk or shader issue then we'll have to fix it within Juiced somehow

Updated by Caboose:

> Semi fixed:
Moon is now rendered however its orbit path is still borked and this seems to be due to mover related issues in the chunk directly.
Lack there of data, Thanks CDPB.
For now moon will render and has been forced to stay still.
The moon shadow has also been removed because something else can still randomly flip the moon upside down and due to this it can look weird in game. We might need a poll for the shadow to be enabled or disabled however.

**Comment by Clippy95** [comment]
Fixed with [this](https://github.com/kobraworksmodding/Saints-Row-2-Juiced-Patch/pull/69), now it matches consoles

**Comment by CabooseSayzWTF** [comment]
Even tho this is closed, I will comment further. It matches console parity with the fixed orbit, things that still lack are black void. < Requires a mesh edit. And moonscale still doesn't properly work correctly from time_of_day xtbl edits, where on console it does.
EDIT: 4/27/26, moonscale has been figured out and fixed and will be in later updates.
